apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: alexapp1
  name: alexapp1
  namespace: alex
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alexapp1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: alexapp1
    spec:
      containers:
      - image: dockerashu/ashumobi:appv1
        name: alexmobi
        ports:
        - containerPort: 80
        resources: {}
        
## adding service with nodeport 
---

apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: alexsvc1
  name: alexsvc1
  namespace: alex
spec:
  ports:
  - name: 1234-80
    port: 1234
    protocol: TCP
    targetPort: 80
  selector: # need to match label of pods 
    app: alexapp1
  type: NodePort
status:
  loadBalancer: {}
